#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../MPC-master/mwc.pl -type make .
#
#----------------------------------------------------------------------------


all: Promises Tests-target

depend: Promises-depend Tests-target-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Promises $(@)
	@cd Tests && $(MAKE) -f Makefile.Tests $(@)

.PHONY: Promises
Promises:
	@$(MAKE) -f Makefile.Promises all

.PHONY: Promises-depend
Promises-depend:
	@$(MAKE) -f Makefile.Promises depend

.PHONY: Tests-target
Tests-target:
	@cd Tests && $(MAKE) -f Makefile.Tests all

.PHONY: Tests-target-depend
Tests-target-depend:
	@cd Tests && $(MAKE) -f Makefile.Tests depend

project_name_list:
	@echo Promises
	@echo Tests-target
